image: alpine:latest

include:
 - template: Container-Scanning.gitlab-ci.yml
 - template: SAST.gitlab-ci.yml

variables:
  SAST_GOSEC_LEVEL: 2
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind
  - ssh:latest

stages:
  - build
  - test

build:
  image: docker:dind
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
