before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://reg.bugfisch.net


image: reg.bugfisch.net/puppet/testrunner:latest



stages:
  - build
  - test
  - run




build:
  image: 
  stage: build
  script:
    - 


include:
 - template: Container-Scanning.gitlab-ci.yml
 - template: SAST.gitlab-ci.yml

variables:
  SAST_GOSEC_LEVEL: 2
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind
  - ssh:latest

stages:
  - build
  - test

build:
  
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker build -t $IMAGE .
    - docker push $IMAGE
