image: ruby:2.5

variables:
  PYTHONPATH: '$PYTHONPATH:./lib'

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y pylint3 python3-argcomplete python3-yaml python3-pip python3-gnupg python3-wget python3-psutil tree git
  - pip3 install python-gnupg python-yubico
  - tree

build:
  stage: build
  script:
    - sed -i "s/^.*url = git@bugfisch.net:\(.*\)/\turl = https:\/\/d0n:$GLTOKEN@bugfisch.net\/\1/" .gitmodules
    - git submodule update --init --recursive
    - pylint3 --rcfile=.pylintrc -E ../pwclip
