before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD https://reg.bugfisch.net

image: reg.bugfisch.net/puppet/testrunner:latest

include:
 - template: Container-Scanning.gitlab-ci.yml
 - template: SAST.gitlab-ci.yml

variables:
  DOCKER_DRIVER: overlay2
  SAST_GOSEC_LEVEL: 2
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:stable-dind

stages:
  - build
  - test
  - staging

mkimage:
  stage: build
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker build -t $IMAGE .
    - docker push $IMAGE

container_scanning:
  stage: test
  variables:
    GIT_STRATEGY: fetch

#self_test:
staging:
  stage: release
  script:
    - lama bpy -SCdmic bdist_deb sdist_dsc sdist bdist upload test d0n@janeiskla.de:rpo/python/pwclip

