image: ruby:2.5

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y pylint3 python3-argcomplete python3-yaml

build:
  stage: build
  script:
    - pylint3 --rcfile=.pylintrc -E ../pwclip
