image: ruby:2.5

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y pylint3

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - pylint3 .
