image: ruby:2.5

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y pylint3

build:
  stage: build
  script:
    - pylint3 --disable=bad-continuation,too-many-arguments,too-many-locals,too-many-branches,invalid-name,multiple-statements,duplicate-code --indent-string='\t' .
