image: docker:stable-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - apt-get update
    - apt-get -y upgrade
    - apt-get install -y pylint3
    - git submodule update --init --recursive
    - pylint3 .
