# This file was auto-generated by salt's setup on Friday, 25 March 2016 @ 16:03:56 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion( 2015, 8, 8, 2, 0, 0, None )
